# app/config/config.yml
cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #cmf_routing.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
    templates:
        tulsie_home:
            path: 'TulsiePageBundle::tulsie_home.html.twig'
            name: 'tulsie home'
            containers:
                 header:
                     name: Header
                 content_top:
                     name: Top content
                 content:
                     name: Main content
                 content_bottom:
                     name: Bottom content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                     HHHHHHHH
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                     FFFFFFFF

                 mapping:
                     H: header
                     T: content_top
                     C: content
                     B: content_bottom
                     F: footer
        default:
            path: 'TulsiePageBundle::tulsie_layout.html.twig'
            name: 'tulsie default'
            containers:
                 header:
                     name: Header
                 content_top:
                     name: Top content
                 content:
                     name: Main content
                 content_bottom:
                     name: Bottom content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                     HHHHHHHH
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                     FFFFFFFF

                 mapping:
                     H: header
                     T: content_top
                     C: content
                     B: content_bottom
                     F: footer
    multisite: host
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false} # disable decoration for homepage, key - is a page route

    default_template: default # template key from templates section, used as default for pages
    templates:
        default:  { path: 'SonataPageBundle::layout.html.twig',          name: 'default' }
        2columns: { path: 'SonataPageBundle::2columns_layout.html.twig', name: '2 columns layout' }

    # manage the http errors
    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error


sonata_admin:
    assets:
        javascripts:
            - bower_components/jquery/dist/jquery.min.js
            - bower_components/jquery.scrollTo/jquery.scrollTo.min.js
            - bower_components/jqueryui/ui/minified/jquery-ui.min.js
            - bower_components/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonatapage/sonata-page.back.min.js
            - bower_components/admin-lte/dist/js/app.min.js
            - bower_components/admin-lte/dist/js/demo.js
            - bower_components/slimScroll/jquery.slimscroll.min.js
            - bower_components/moment/min/moment.min.js
            - bower_components/admin-lte/bootstrap/js/bootstrap.min.js
            - bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js



        stylesheets:
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.css
            - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/tree.css
            - bower_components/admin-lte/bootstrap/css/bootstrap.min.css
            - bower_components/admin-lte/dist/css/AdminLTE.min.css
            - bower_components/admin-lte/dist/css/skins/_all-skins.min.css
            - bower_components/admin-lte/plugins/datepicker/datepicker3.css
            - bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
